polls/routes/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from django.contrib import admin
from ..views import views, text, success, list

urlpatterns = [
    path('', views.index, name='index'),
    path('form/', text.index, name='index'),
    path('submit/', success.index, name='index'),
    path('form/login/', text.login, name='login'),
    path('admin/', admin.site.urls),
    path('list/', list.list_data, name='list_data'), 
]

polls/models.py
from django.db import models

# Create your models here.

class Forms(models.Model):
    name = models.TextField(max_length=100)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    category = models.CharField(max_length=15)

polls/views/forms.py
from django import forms
from django.forms.widgets import DateInput

CATS = [
    ('1', 'cat1'),
    ('2', 'cat2')
]
DATE_INPUT_FORMATS = ['%d-%m-%Y']
class FormName(forms.Form) :
    name = forms.CharField()
    start_date = forms.DateField(widget=DateInput({'class': 'datepicker'}))
    end_date = forms.DateField(widget=DateInput({'class': 'datepicker'}))
    category = forms.ChoiceField(
        widget=forms.Select, choices=CATS
    )

polls/views/list.py
from django.shortcuts import render
from ..models import Forms

def list_data(request):
    list = Forms.objects.values()
    set = []
    for data in list:
        dict = {
            'name': data['name'],
            'start_date': data['start_date'],
            'end_date': data['end_date'],
            'category': data['category'],
        }
        set.append(dict)
    return render(request, 'list.html',{'list': set})

polls/views/success.py
from django.http import HttpResponse

def index(request):
    return HttpResponse("Successfully Submitted!")

polls/views/text.py
from django import forms
from django.shortcuts import redirect, render
from django.shortcuts import render
from . import forms
from ..models import Forms
from django.http import JsonResponse
import json

# Create your views here.

def index(request):
    form = forms.FormName()
    if request.method == 'POST':
        form = forms.FormName(request.POST)
    
    if form.is_valid():
        print("Form validation successful! See console for information:")
        print("Name: "+form.cleaned_data['name'])
        print(form.cleaned_data['start_date'])
        print(form.cleaned_data['end_date'])
        print("Category "+form.cleaned_data['category'])
        Forms.objects.create(name = form.cleaned_data['name'], start_date = form.cleaned_data['start_date'], end_date = form.cleaned_data['end_date'], category = form.cleaned_data['category'],)
        return redirect('/list')

    return render(request, 'form.html', {'form': form})

def submit(request):
    print(request)

def login(request):
    status = 'true'
    data = json.loads(request.body)
    status = 'false'
    if status == 'false':
        return JsonResponse({'error': "User not found"}, status = 423)
    else :
        return JsonResponse({}, status = 200)

polls/views/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms

# Create your views here.

def index(request):
    return HttpResponse("Hello World. Nice to see you")

polls/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Coding for beginners</title>
    <style>
    .error{
        color: red;
        padding-left: 4px; 
    }
      /* dynamic p */
      p {
        height: 31px;
        margin-bottom: 1.5rem !important;
        align-items: center;
      }

      input[type='text']:disabled {
        cursor: default;
        background-color: #e9ecef !important;
        border-color: rgba(118, 118, 118, 0.3);
      }

      .datepicker,
      #id_name {
        padding-top: 0.25rem !important;
        padding-bottom: 0.25rem !important;
        padding-left: 0.5rem !important;
        font-size: 0.875rem !important;
        border-radius: 0.2rem !important;
        width: 100%;
        -moz-padding-start: calc(0.75rem - 3px);
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        background-color: #fff;
        background-repeat: no-repeat;
        background-position: right 0.75rem center;
        background-size: 16px 12px;
        border: 1px solid #ced4da;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
      }

      p input:focus {
        border-color: #86b7fe;
        outline: 0;
        box-shadow: 0 0 0 0.25rem rgb(13 110 253 / 25%);
      }

      .setHeight {
        height: 100vh;
      }

      /* #submit-poll {
        background: pink;
      } */
      #submit-poll p {
        display: flex;
        /* align-items: center; */
      }

      .card {
        min-width: 300px !important;
      }

      /* default select */
      select:hover {
        cursor: pointer;
      }

      /* custom select */
      #id_category {
        padding-top: 0.25rem;
        padding-bottom: 0.25rem;
        padding-left: 0.5rem;
        font-size: 0.875rem;
        border-radius: 0.2rem;
        display: block;
        width: 100%;
        -moz-padding-start: calc(0.75rem - 3px);
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        background-color: #fff;
        background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M2 5l6 6 6-6'/%3e%3c/svg%3e");
        background-repeat: no-repeat;
        background-position: right 0.75rem center;
        background-size: 16px 12px;
        border: 1px solid #ced4da;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
      }

      #id_category:focus {
        border-color: #86b7fe;
        outline: 0;
        box-shadow: 0 0 0 0.25rem rgb(13 110 253 / 25%);
      }

      /* custom margin below each input */
      .custom-margin-select {
        margin-bottom: 1.5rem !important;
        align-items: center;
      }

      /* custom label spacing */
      label {
        min-width: 10ch !important;
      }
    </style>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>
<link
  rel="stylesheet"
  href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"
/>
<!-- Bootstrap CSS -->
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
<!-- Option 1: Bootstrap Bundle with Popper -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"
></script>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script>

<script>
  $(document).ready(function () {
    $(".datepicker").datepicker();
    localStorage.setItem("loggedIn", false);
    $("input#id_name").attr("disabled", "true");
    $("input#id_start_date").attr("disabled", "true");
    $("input#id_end_date").attr("disabled", "true");
    $("select#id_category").attr("disabled", "true");
    $("select#exchanges").attr("disabled", "true");
    $("input").change(() => {
      let status = true;
      if (!$("input#id_name").val()) {
        status = false;
      }
      if (!$("input#id_start_date").val()) {
        status = false;
      }
      if (!$("input#id_end_date").val()) {
        status = false;
      }
      if (status) {
        $('input[name="submit"]').removeAttr("disabled");
      }
    });
    // $(document).on('change', 'select#sources', function(e){
    //     console.log($(this).val())
    // })
    $("select#sources").change((e) => {
      $("input#id_name").attr("disabled", "true");
      $("input#id_start_date").attr("disabled", "true");
      $("input#id_end_date").attr("disabled", "true");
      $("select#id_category").attr("disabled", "true");
      $("select#exchanges").attr("disabled", "true");
      const value = e.target.value;
      if (value == "2" || value == "4") {
        Swal.fire({
          title: "Login",
          html:
            '<input id="username" class="swal2-input" type="text" placeholder="User Name" required>' +
            '<input id="password" class="swal2-input" type="password" placeholder="Password" required>' +
            '{% csrf_token %}' +
            '<span style="color: red;" id="error"></span>',
          showCancelButton: true,
          confirmButtonText: "Confirm",
          showLoaderOnConfirm: true,
          preConfirm: () => {
            return fetch(`login/`, {
              // Adding method type
              method: "POST",

              // Adding body or contents to send
              body: JSON.stringify({
                username: $("input#username").val(),
                password: $("input#password").val(),
              }),

              // Adding headers to the request
              headers: {
                "Content-type": "application/json; charset=UTF-8",
                "X-CSRFToken": $('input[name="csrfmiddlewaretoken"]').val(),
              },
            }).then((response) => {
              if (!response.ok) {
                localStorage.setItem("loggedIn", false);
                Swal.close();
                toastr.error("Login Failed", "Error!");
                return;
              } else {
                toastr.success("Logged In successfully", "Success!");
                localStorage.setItem("loggedIn", true);
                $('input[type="text"]').removeAttr("disabled");
                $("select").removeAttr("disabled");
                return response.json();
              }
            });
          },
          allowOutsideClick: () => !Swal.isLoading(),
        }).then((result) => {
          if (result.isConfirmed) {
            // Swal.fire({
            //     title: `${result.value.login}'s avatar`,
            //     imageUrl: result.value.avatar_url
            // })
          }
        });
      } else {
        $('input[type="text"]').removeAttr("disabled");
        $("select").removeAttr("disabled");
      }
    });

    $("form#submit-poll").validate({
      name: {
        required: true,
      },
      start_date: {
        required: true,
      },
      end_date: {
        required: true,
      },
      category: {
        required: true,
      },
    });
  });
</script>

polls/templates/form.html
{% extends "base.html" %}
{% block content %}
<div class="col-12 d-flex align-items-center form-layout setHeight">
  <div class="card mx-auto my-auto bg-blue shadow p-4">
    <form method="POST" id="submit-poll">
      <div class="custom-margin-select d-flex">
        <label for="sources">Sources</label>
        <select name="sources" id="sources" class="form-select form-select-sm">
          <option value="" class="fst-italic">--Select Source--</option>
          <option value="1">Market</option>
          <option value="2">Trade</option>
          <option value="3">Cross</option>
          <option value="4">All</option>
        </select>
      </div>
      {% csrf_token %} {{form.as_p}}
      <div class="custom-margin-select d-flex">
        <label for="exchanges">Exchange</label>
        <select
          name="exchanges"
          id="exchanges"
          class="form-select form-select-sm"
        >
          <option value="" class="fst-italic">--Select Options--</option>
          <option value="1">Market</option>
          <option value="2">Trade</option>
          <option value="3">Cross</option>
          <option value="4">All</option>
        </select>
      </div>
      <input
        type="submit"
        value="Submit"
        disabled
        class="btn btn-primary btn-md"
        name="submit"
      />
    </form>
  </div>
</div>
{% endblock %}

polls/templates/list.html
{% extends "base.html" %}
{% block content %}
<ul>
    {% for data in list %}
        <li>
            {{ data.name }}
        </li>
        <li>
            {{ data.category }}
        </li>
        <li>
            {{ data.start_date }}
        </li>
        <li>
            {{ data.end_date }}
        </li>
        <li>
        </li>
    {% endfor %}
</ul>
{% endblock %}